# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ibb1pvbQP_0eGX0_ZEYuyCKxzwvkBn3l
"""
#primeira funcao básica de demonstração
variavel_1 = 10 
variavel_2 = 5

operacao = variavel_1 * variavel_2

print("o resultado é ", operacao)
##declarando a posição do objeto
cancao = "roda mundo roda gigante, roda moinho roda peão..."
print(cancao.upper())
#para função, sempre parentes. Utilizasse colchetes para listas e tuplas.
posicao = cancao.find("roda gigante")
print(posicao)

#listas
lista = ['Bruna Dalmagro, Matheus, Ebac, Python, Curso, Ciencia de Dados']
print(lista)

lista_1 = lista.pop(0)
print(lista_1)

lista.insert(1,lista_1)
print(lista)

json = [{
   "nome" : "John Banana",
   "idade" : 22,
   "identidadeSecreta" : "Unknow"
},
{   "nome" : "Adalbert Sales",
   "idade" : 30,
   "identidadeSecreta" : "Psicopato"
},
 {  "nome" : "Rian Aphelio",
   "idade" : 28,
   "identidadeSecreta" : "Minino da portera"
  }
]

for dadosAgentes in json:
    print(dadosAgentes)

for dadoNome in json:
  print(dadoNome['nome'])
